### PR TITLE
test(x/ecocredit): move regen prefix configuration into module root

### PR DESCRIPTION
**Pull request by wgwz**
## Description

Closes: https://github.com/regen-network/regen-ledger/issues/1243

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed 
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by ryanchristo** [comment]
Thanks for the contribution @wgwz! This is a step in the right direction. The configuration was previously on a test setup basis so the next step will be updating the addresses used in tests that did not have the configuration.

You can run `make test` locally to see which tests are failing. You can also see which tests are currently failing by looking at the details of the CI job: https://github.com/regen-network/regen-ledger/runs/7265917088?check_suite_focus=true.

It looks like `MsgCreate`, `MsgPut`, and `MsgTake` in the basket submodule are the first set of tests failing, so you need to update the use of cosmos addresses to regen addresses in the feature files (e.g.`basket/features/msg_create.feature`).

`cosmos1depk54cuajgkzea6zpgkq36tnjwdzv4afc3d27` -> `regen1depk54cuajgkzea6zpgkq36tnjwdzv4ak663u6`

After updating the addresses in the basket submodule, you'll find more tests failing in marketplace and elsewhere, so you'll need to update the addresses within the ecocredit module wherever tests are failing due to the use of a cosmos address.

**Comment by wgwz** [comment]
@ryanchristo thanks for the pointers! following those suggestions i think this should be a bit closer now. i *think* the tests were passing in my local environment. at the very least, i know i made some failures go away (i think... 😅 )

that said, i wanted to ask about some output i'm seeing when running the tests. i'm getting lots of warnings, should i be concerned about those? do we have known fixes/workarounds? i'm also seeing some stuff mark as "FAIL".

```
Unit tests
Testing Module .
# github.com/keybase/go-keychain
cgo-gcc-prolog:81:11: warning: 'SecKeychainCreate' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:301:10: note: 'SecKeychainCreate' has been explicitly marked deprecated here
cgo-gcc-prolog:139:11: warning: 'SecKeychainLock' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:357:10: note: 'SecKeychainLock' has been explicitly marked deprecated here
cgo-gcc-prolog:159:11: warning: 'SecKeychainOpen' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:287:10: note: 'SecKeychainOpen' has been explicitly marked deprecated here
cgo-gcc-prolog:183:11: warning: 'SecKeychainUnlock' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:347:10: note: 'SecKeychainUnlock' has been explicitly marked deprecated here
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here
# github.com/CosmWasm/wasmvm/api
ld: warning: ignoring file ../../go/pkg/mod/github.com/!cosm!wasm/wasmvm@v1.0.0-beta5/api/libwasmvm.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_analyze_code", referenced from:
      __cgo_752f6d91b618_C2func_analyze_code in _x004.o
      __cgo_752f6d91b618_Cfunc_analyze_code in _x004.o
     (maybe you meant: __cgo_752f6d91b618_Cfunc_analyze_code, __cgo_752f6d91b618_C2func_analyze_code )
  "_destroy_unmanaged_vector", referenced from:
      __cgo_752f6d91b618_Cfunc_destroy_unmanaged_vector in _x006.o
     (maybe you meant: __cgo_752f6d91b618_Cfunc_destroy_unmanaged_vector)
  "_execute", referenced from:
      __cgo_752f6d91b618_C2func_execute in _x004.o
      __cgo_752f6d91b618_Cfunc_execute in _x004.o
     (maybe you meant: __cgo_752f6d91b618_C2func_execute, __cgo_752f6d91b618_Cfunc_execute )
  "_get_metrics", referenced from:
      __cgo_752f6d91b618_C2func_get_metrics in _x004.o
      __cgo_752f6d91b618_Cfunc_get_metrics in _x004.o
     (maybe you meant: __cgo_752f6d91b618_Cfunc_get_metrics, __cgo_752f6d91b618_C2func_get_metrics )
  "_ibc_channel_close", referenced from:
      __cgo_752f6d91b618_C2func_ibc_channel_close in _x004.o
      __cgo_752f6d91b618_Cfunc_ibc_channel_close in _x004.o
     (maybe you meant: __cgo_752f6d91b618_Cfunc_ibc_channel_close, __cgo_752f6d91b618_C2func_ibc_channel_close )
  "_ibc_channel_connect", referenced from:
      __cgo_752f6d91b618_C2func_ibc_channel_connect in _x004.o
      __cgo_752f6d91b618_Cfunc_ibc_channel_connect in _x004.o
     (maybe you meant: __cgo_752f6d91b618_Cfunc_ibc_channel_connect, __cgo_752f6d91b618_C2func_ibc_channel_connect )
  "_ibc_channel_open", referenced from:
      __cgo_752f6d91b618_C2func_ibc_channel_open in _x004.o
      __cgo_752f6d91b618_Cfunc_ibc_channel_open in _x004.o
     (maybe you meant: __cgo_752f6d91b618_C2func_ibc_channel_open, __cgo_752f6d91b618_Cfunc_ibc_channel_open )
  "_ibc_packet_ack", referenced from:
      __cgo_752f6d91b618_C2func_ibc_packet_ack in _x004.o
      __cgo_752f6d91b618_Cfunc_ibc_packet_ack in _x004.o
     (maybe you meant: __cgo_752f6d91b618_Cfunc_ibc_packet_ack, __cgo_752f6d91b618_C2func_ibc_packet_ack )
  "_ibc_packet_receive", referenced from:
      __cgo_752f6d91b618_C2func_ibc_packet_receive in _x004.o
      __cgo_752f6d91b618_Cfunc_ibc_packet_receive in _x004.o
     (maybe you meant: __cgo_752f6d91b618_Cfunc_ibc_packet_receive, __cgo_752f6d91b618_C2func_ibc_packet_receive )
  "_ibc_packet_timeout", referenced from:
      __cgo_752f6d91b618_C2func_ibc_packet_timeout in _x004.o
      __cgo_752f6d91b618_Cfunc_ibc_packet_timeout in _x004.o
     (maybe you meant: __cgo_752f6d91b618_Cfunc_ibc_packet_timeout, __cgo_752f6d91b618_C2func_ibc_packet_timeout )
  "_init_cache", referenced from:
      __cgo_752f6d91b618_C2func_init_cache in _x004.o
      __cgo_752f6d91b618_Cfunc_init_cache in _x004.o
     (maybe you meant: __cgo_752f6d91b618_C2func_init_cache, __cgo_752f6d91b618_Cfunc_init_cache )
  "_instantiate", referenced from:
      __cgo_752f6d91b618_C2func_instantiate in _x004.o
      __cgo_752f6d91b618_Cfunc_instantiate in _x004.o
     (maybe you meant: __cgo_752f6d91b618_Cfunc_instantiate, __cgo_752f6d91b618_C2func_instantiate )
  "_load_wasm", referenced from:
      __cgo_752f6d91b618_C2func_load_wasm in _x004.o
      __cgo_752f6d91b618_Cfunc_load_wasm in _x004.o
     (maybe you meant: __cgo_752f6d91b618_Cfunc_load_wasm, __cgo_752f6d91b618_C2func_load_wasm )
  "_migrate", referenced from:
      __cgo_752f6d91b618_C2func_migrate in _x004.o
      __cgo_752f6d91b618_Cfunc_migrate in _x004.o
     (maybe you meant: __cgo_752f6d91b618_Cfunc_migrate, __cgo_752f6d91b618_C2func_migrate )
  "_new_unmanaged_vector", referenced from:
      __cgo_752f6d91b618_Cfunc_new_unmanaged_vector in _x006.o
     (maybe you meant: __cgo_752f6d91b618_Cfunc_new_unmanaged_vector)
  "_pin", referenced from:
      __cgo_752f6d91b618_C2func_pin in _x004.o
      __cgo_752f6d91b618_Cfunc_pin in _x004.o
     (maybe you meant: __cgo_752f6d91b618_Cfunc_pin, __cgo_752f6d91b618_C2func_pin )
  "_query", referenced from:
      __cgo_752f6d91b618_C2func_query in _x004.o
      __cgo_752f6d91b618_Cfunc_query in _x004.o
     (maybe you meant: __cgo_752f6d91b618_Cfunc_query, __cgo_752f6d91b618_C2func_query )
  "_release_cache", referenced from:
      __cgo_752f6d91b618_Cfunc_release_cache in _x004.o
     (maybe you meant: __cgo_752f6d91b618_Cfunc_release_cache)
  "_reply", referenced from:
      __cgo_752f6d91b618_C2func_reply in _x004.o
      __cgo_752f6d91b618_Cfunc_reply in _x004.o
     (maybe you meant: __cgo_752f6d91b618_C2func_reply, __cgo_752f6d91b618_Cfunc_reply )
  "_save_wasm", referenced from:
      __cgo_752f6d91b618_C2func_save_wasm in _x004.o
      __cgo_752f6d91b618_Cfunc_save_wasm in _x004.o
     (maybe you meant: __cgo_752f6d91b618_C2func_save_wasm, __cgo_752f6d91b618_Cfunc_save_wasm )
  "_sudo", referenced from:
      __cgo_752f6d91b618_C2func_sudo in _x004.o
      __cgo_752f6d91b618_Cfunc_sudo in _x004.o
     (maybe you meant: __cgo_752f6d91b618_C2func_sudo, __cgo_752f6d91b618_Cfunc_sudo )
  "_unpin", referenced from:
      __cgo_752f6d91b618_C2func_unpin in _x004.o
      __cgo_752f6d91b618_Cfunc_unpin in _x004.o
     (maybe you meant: __cgo_752f6d91b618_Cfunc_unpin, __cgo_752f6d91b618_C2func_unpin )
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
FAIL	github.com/regen-network/regen-ledger/v4/app [build failed]
FAIL	github.com/regen-network/regen-ledger/v4/app/regen/cmd [build failed]
FAIL	github.com/regen-network/regen-ledger/v4/app/testsuite [build failed]
Testing Module ./api
?   	github.com/regen-network/regen-ledger/api/regen/data/v1	[no test files]
?   	github.com/regen-network/regen-ledger/api/regen/data/v1alpha2	[no test files]
?   	github.com/regen-network/regen-ledger/api/regen/ecocredit/basket/v1	[no test files]
?   	github.com/regen-network/regen-ledger/api/regen/ecocredit/marketplace/v1	[no test files]
?   	github.com/regen-network/regen-ledger/api/regen/ecocredit/orderbook/v1alpha1	[no test files]
?   	github.com/regen-network/regen-ledger/api/regen/ecocredit/v1	[no test files]
?   	github.com/regen-network/regen-ledger/api/regen/ecocredit/v1alpha1	[no test files]
?   	github.com/regen-network/regen-ledger/api/regen/group/v1alpha1	[no test files]
Testing Module ./types
# github.com/keybase/go-keychain
cgo-gcc-prolog:81:11: warning: 'SecKeychainCreate' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:301:10: note: 'SecKeychainCreate' has been explicitly marked deprecated here
cgo-gcc-prolog:139:11: warning: 'SecKeychainLock' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:357:10: note: 'SecKeychainLock' has been explicitly marked deprecated here
cgo-gcc-prolog:159:11: warning: 'SecKeychainOpen' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:287:10: note: 'SecKeychainOpen' has been explicitly marked deprecated here
cgo-gcc-prolog:183:11: warning: 'SecKeychainUnlock' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:347:10: note: 'SecKeychainUnlock' has been explicitly marked deprecated here
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here
ok  	github.com/regen-network/regen-ledger/types	(cached)
ok  	github.com/regen-network/regen-ledger/types/eth	(cached)
ok  	github.com/regen-network/regen-ledger/types/math	(cached)
?   	github.com/regen-network/regen-ledger/types/module	[no test files]
?   	github.com/regen-network/regen-ledger/types/module/client/cli	[no test files]
?   	github.com/regen-network/regen-ledger/types/module/client/grpc_gateway	[no test files]
?   	github.com/regen-network/regen-ledger/types/module/server	[no test files]
ok  	github.com/regen-network/regen-ledger/types/ormstore	(cached)
?   	github.com/regen-network/regen-ledger/types/ormutil	[no test files]
?   	github.com/regen-network/regen-ledger/types/testutil	[no test files]
?   	github.com/regen-network/regen-ledger/types/testutil/cli	[no test files]
?   	github.com/regen-network/regen-ledger/types/testutil/network	[no test files]
Testing Module ./x/data
# github.com/keybase/go-keychain
cgo-gcc-prolog:81:11: warning: 'SecKeychainCreate' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:301:10: note: 'SecKeychainCreate' has been explicitly marked deprecated here
cgo-gcc-prolog:139:11: warning: 'SecKeychainLock' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:357:10: note: 'SecKeychainLock' has been explicitly marked deprecated here
cgo-gcc-prolog:159:11: warning: 'SecKeychainOpen' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:287:10: note: 'SecKeychainOpen' has been explicitly marked deprecated here
cgo-gcc-prolog:183:11: warning: 'SecKeychainUnlock' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:347:10: note: 'SecKeychainUnlock' has been explicitly marked deprecated here
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here
ok  	github.com/regen-network/regen-ledger/x/data	(cached)
?   	github.com/regen-network/regen-ledger/x/data/client	[no test files]
?   	github.com/regen-network/regen-ledger/x/data/client/testsuite	[no test files]
?   	github.com/regen-network/regen-ledger/x/data/mocks	[no test files]
?   	github.com/regen-network/regen-ledger/x/data/module	[no test files]
ok  	github.com/regen-network/regen-ledger/x/data/server	(cached)
ok  	github.com/regen-network/regen-ledger/x/data/server/hasher	(cached)
ok  	github.com/regen-network/regen-ledger/x/data/server/testsuite	(cached)
?   	github.com/regen-network/regen-ledger/x/data/simulation	[no test files]
Testing Module ./x/ecocredit
# github.com/keybase/go-keychain
cgo-gcc-prolog:81:11: warning: 'SecKeychainCreate' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:301:10: note: 'SecKeychainCreate' has been explicitly marked deprecated here
cgo-gcc-prolog:139:11: warning: 'SecKeychainLock' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:357:10: note: 'SecKeychainLock' has been explicitly marked deprecated here
cgo-gcc-prolog:159:11: warning: 'SecKeychainOpen' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:287:10: note: 'SecKeychainOpen' has been explicitly marked deprecated here
cgo-gcc-prolog:183:11: warning: 'SecKeychainUnlock' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:347:10: note: 'SecKeychainUnlock' has been explicitly marked deprecated here
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here
?   	github.com/regen-network/regen-ledger/x/ecocredit	[no test files]
ok  	github.com/regen-network/regen-ledger/x/ecocredit/basket	(cached)
ok  	github.com/regen-network/regen-ledger/x/ecocredit/client	(cached)
ok  	github.com/regen-network/regen-ledger/x/ecocredit/client/basket	(cached)
?   	github.com/regen-network/regen-ledger/x/ecocredit/client/core	[no test files]
ok  	github.com/regen-network/regen-ledger/x/ecocredit/client/marketplace	(cached)
?   	github.com/regen-network/regen-ledger/x/ecocredit/client/testsuite	[no test files]
# github.com/regen-network/regen-ledger/x/ecocredit/core [github.com/regen-network/regen-ledger/x/ecocredit/core.test]
core/msg_bridge_receive_test.go:12:2: imported and not used: "github.com/cosmos/cosmos-sdk/types" as sdk
core/msg_bridge_test.go:10:2: imported and not used: "github.com/cosmos/cosmos-sdk/types" as sdk
core/msg_cancel_test.go:12:2: imported and not used: "github.com/cosmos/cosmos-sdk/types" as sdk
core/msg_create_batch_test.go:12:2: imported and not used: "github.com/cosmos/cosmos-sdk/types" as sdk
core/msg_create_class_test.go:12:2: imported and not used: "github.com/cosmos/cosmos-sdk/types" as sdk
core/msg_create_project_test.go:12:2: imported and not used: "github.com/cosmos/cosmos-sdk/types" as sdk
core/msg_mint_batch_credits_test.go:10:2: imported and not used: "github.com/cosmos/cosmos-sdk/types" as sdk
core/msg_retire_test.go:10:2: imported and not used: "github.com/cosmos/cosmos-sdk/types" as sdk
core/msg_seal_batch_test.go:10:2: imported and not used: "github.com/cosmos/cosmos-sdk/types" as sdk
core/msg_send_test.go:10:2: imported and not used: "github.com/cosmos/cosmos-sdk/types" as sdk
core/msg_send_test.go:10:2: too many errors
FAIL	github.com/regen-network/regen-ledger/x/ecocredit/core [build failed]
ok  	github.com/regen-network/regen-ledger/x/ecocredit/marketplace	(cached)
ok  	github.com/regen-network/regen-ledger/x/ecocredit/migrations/v3	(cached)
?   	github.com/regen-network/regen-ledger/x/ecocredit/mocks	[no test files]
ok  	github.com/regen-network/regen-ledger/x/ecocredit/module	(cached)
?   	github.com/regen-network/regen-ledger/x/ecocredit/orderbook	[no test files]
ok  	github.com/regen-network/regen-ledger/x/ecocredit/server	(cached)
ok  	github.com/regen-network/regen-ledger/x/ecocredit/server/basket	(cached)
ok  	github.com/regen-network/regen-ledger/x/ecocredit/server/core	(cached)
ok  	github.com/regen-network/regen-ledger/x/ecocredit/server/marketplace	(cached)
?   	github.com/regen-network/regen-ledger/x/ecocredit/server/testsuite	[no test files]
ok  	github.com/regen-network/regen-ledger/x/ecocredit/server/utils	(cached)
ok  	github.com/regen-network/regen-ledger/x/ecocredit/simulation	(cached)
?   	github.com/regen-network/regen-ledger/x/ecocredit/simulation/basket	[no test files]
?   	github.com/regen-network/regen-ledger/x/ecocredit/simulation/marketplace	[no test files]
?   	github.com/regen-network/regen-ledger/x/ecocredit/simulation/utils	[no test files]
FAIL
Testing Module ./x/group
# github.com/keybase/go-keychain
cgo-gcc-prolog:81:11: warning: 'SecKeychainCreate' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:301:10: note: 'SecKeychainCreate' has been explicitly marked deprecated here
cgo-gcc-prolog:139:11: warning: 'SecKeychainLock' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:357:10: note: 'SecKeychainLock' has been explicitly marked deprecated here
cgo-gcc-prolog:159:11: warning: 'SecKeychainOpen' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:287:10: note: 'SecKeychainOpen' has been explicitly marked deprecated here
cgo-gcc-prolog:183:11: warning: 'SecKeychainUnlock' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:347:10: note: 'SecKeychainUnlock' has been explicitly marked deprecated here
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here
ok  	github.com/regen-network/regen-ledger/x/group	(cached)
?   	github.com/regen-network/regen-ledger/x/group/client	[no test files]
?   	github.com/regen-network/regen-ledger/x/group/client/testsuite	[no test files]
?   	github.com/regen-network/regen-ledger/x/group/exported	[no test files]
?   	github.com/regen-network/regen-ledger/x/group/module	[no test files]
ok  	github.com/regen-network/regen-ledger/x/group/server	(cached)
?   	github.com/regen-network/regen-ledger/x/group/server/testsuite	[no test files]
?   	github.com/regen-network/regen-ledger/x/group/simulation	[no test files]
```

**Comment by ryanchristo** [comment]
> that said, i wanted to ask about some output i'm seeing when running the tests. i'm getting lots of warnings, should i be concerned about those? do we have known fixes/workarounds? i'm also seeing some stuff mark as "FAIL".

Oh boy. I've never actually seen the output for tests when running on a Mac.

All the warnings related to go-keychain are ok to ignore. This has been a known issue and I think we're just waiting for the later version of the sdk although we might be able to use a replace directive in the meantime.

The failed app tests are also not an issue for me but they will be resolved with #1255. I didn't realize these were failing when running tests locally on a Mac but the reason makes sense.

The only errors I'm seeing now are [these errors](https://gist.github.com/wgwz/259eced61244492298bf5137e6a79ad1#file-out-txt-L181-L191), which can be resolved by simply removing the `github.com/cosmos/cosmos-sdk/types` import in the files that no longer make use of the package.

**Comment by ryanchristo** [comment]
Also, you'll need to resolve conflicts before the CI can run. The `patch_test.go` file was updated since you started working on this pull request. There's also a new `init` function in there that is no longer needed:

https://github.com/regen-network/regen-ledger/pull/1248#discussion_r917444733

**Comment by ryanchristo** [comment]
Other than the import errors and resolving the conflicts, this looks great! Thank you!

**Review by technicallyty — APPROVED** [review]

**Comment by wgwz** [comment]
Thanks @ryanchristo feels good to have a contribution, thanks for the guidance on it :-)

**Pull request merged**
