### PR TITLE
fix: default values for issuance in create batch

### PR DESCRIPTION
**Pull request by atheeshp**
## Description

Closes: #390 

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed 
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Review by aaronc — APPROVED** [review]

**Review by ruhatch — APPROVED** [review]
Nice, thanks.

It seems a bit of a shame that we're parsing all the amounts twice (ValidateBasic and the msg handler), but I can see a clear way around that...

**Comment by aaronc** [comment]
> Nice, thanks.
> 
> 
> 
> It seems a bit of a shame that we're parsing all the amounts twice (ValidateBasic and the msg handler), but I can see a clear way around that...

Actually can't we just populate the Msg and then ValidateBasic gets called? We should test and see

**Comment by blushi** [comment]
> > Nice, thanks.
> > It seems a bit of a shame that we're parsing all the amounts twice (ValidateBasic and the msg handler), but I can see a clear way around that...
> 
> Actually can't we just populate the Msg and then ValidateBasic gets called? We should test and see

@aaronc do you mean in `x/ecocredit/client/tx.go`?

**Comment by blushi** [comment]
On another note, while looking at the changes in msg.go, I thought it would be good to add a test case for it and then I realized that we do have any msg_test.go at all and the test coverage is quite low in the `ecocredit` package in general. I couldn't find any issue that tracks that in particular, should I create one and tag it for v1.1?

**Comment by blushi** [comment]
> > > Nice, thanks.
> > > It seems a bit of a shame that we're parsing all the amounts twice (ValidateBasic and the msg handler), but I can see a clear way around that...
> > 
> > Actually can't we just populate the Msg and then ValidateBasic gets called? We should test and see
> 
> @aaronc do you mean in `x/ecocredit/client/tx.go`?

@aaronc any thoughts?

**Pull request merged**
