### PR TITLE
fix: Use correct REGEN_HOME env in regen sandbox

### PR DESCRIPTION
**Pull request by paul121**
## Description

I believe `REGENHOME` is a semi-incorrect env var for here. I was referenced this regen-sandbox Dockerfile and was getting inconsistent results. It's quite confusing because it seems like it works for some things but not others. Using `REGEN_HOME` is working much better, as seen in this PR: https://github.com/regen-network/regen-ledger/pull/1672

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed 
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Review by ryanchristo — COMMENTED** [review]
Thanks @paul121!

It looks like the `bootstrap.sh` and `setup/utils` both use `REGENHOME`. Can you update?

**Comment by paul121** [comment]
Thanks @ryanchristo - I missed that. Now it makes more sense how this was working :-)

I removed the `regen()` function because it should be necessary. Here is a simple test, demonstrating that running the container the first time creates a localnet + node. Stopping and restarting the container starts where it left off.

```shell

$ docker run -v $(pwd):/regen regen-sandbox:latest
Created genesis. chain-id: regen-sandbox, moniker: test_moniker

No $REGEN_MNEMONIC provided, using generated mnemonic:
    ...........removed

Adding key to keyring for account name: addr1
Adding key to keyring for account name: addr2
Adding key to keyring for account name: addr3
Adding key to keyring for account name: addr4
Adding key to keyring for account name: addr5
Setting up validator (from addr1)...
Genesis transaction written to "/regen/.regen/config/gentx/gentx-cb93edeb49841d6c68fabde235f00b9461ea56c3.json"
Collecting gentxs from /regen/.regen/config/gentx into genesis.json
Starting up regen node...
Node started & state inialized!
^C
$ docker run -v $(pwd):/regen regen-sandbox:latest
Regen home (/regen/.regen) already exists, skipping bootstrap...
Starting up regen node...
Node started & state inialized!
```

**Review by ryanchristo — APPROVED** [review]
tACK. Thanks again @paul121!

**Comment by ryanchristo** [comment]
@mergifyio backport release/v5.0.x

**Pull request merged**
