### PR TITLE
fix(ecocredit/core): wrong key type in class lookup

### PR DESCRIPTION
**Pull request by technicallyty**
## Description

- fixes an issue where the wrong key is used to fetch class 

Closes: n/a

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed 
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Review by ryanchristo — APPROVED** [review]

**Review by aaronc — APPROVED** [review]

**Comment by aaronc** [comment]
Actually shouldn't we have some tests for this? If tests weren't failing before how did we find the error?

**Comment by ryanchristo** [comment]
> Actually shouldn't we have some tests for this? If tests weren't failing before how did we find the error?

Not sure how it was found but we should have tests for this. Either we can update the existing test or we can wait for acceptance tests to be written. I noticed a lot of tests using an assumed key rather than using the key returned when using `InsertReturningId`. This is probably the reason.

**Comment by technicallyty** [comment]
I caught it in my integration test branch, although this seems like something that should definitely be caught at the unit level

**Comment by aaronc** [comment]
Are there some non-required checks that were failing? If so we should make them required

**Comment by ryanchristo** [comment]
> Are there some non-required checks that were failing? If so we should make them required

All checks were passing except for the proto breaking check. Same with the checks merged to master. I think this was something not covered in our unit tests. I will open an issue to audit our existing unit tests with this scenario specifically as an example to make sure we are tracking and addressing.

**Pull request merged**
