### PR TITLE
feat(app): set up post handler for tx tips

### PR DESCRIPTION
**Pull request by technicallyty**
## Description

enables tx tips on the application

Closes: #1331 

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed 
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Review by ryanchristo — CHANGES_REQUESTED** [review]
>  We should first identify potential use cases and then consider including in the next release alongside other v0.46 updates

**Comment by ryanchristo** [comment]
Would be great if you could do a little research on how we might use transaction tips before we implement this.

**Comment by technicallyty** [comment]
> Would be great if you could do a little research on how we might use transaction tips before we implement this.

- user receives ecocredits from send/create_batch/bridge but has no REGEN balance, can then move the credits around w/o having to acquire REGEN (keep in mind, REGEN will still cycle through the system, its just paid for by the fee payer/relayer in exchange for whatever the user's tip is)
- the ol' "staked all my coins but now i can't claim my rewards" problem can be fixed w/ tips 😺 
- validator w/ extra liquid REGEN can setup a market for tips allowing them to earn other IBC coins for regen ledger transactions

also fair warning, we may want to keep this blocked for now as it is technically still beta software. may want to consider waiting till full release

**Comment by ryanchristo** [comment]
On hold until we have automated fee payer infrastructure in place. Until then, using the tips field will error rather than no error with no automated fee payer infrastructure in place.

**Comment by ryanchristo** [comment]
Closing this as we are not planning to implement a fee payer infrastructure and we are considering an alternative (allowing for multiple fees - another solution that chains are using). We can re-open and revisit if we change our mind.

**Pull request closed without merging**
