### PR TITLE
bump tendermint and SDK version

### PR DESCRIPTION
**Pull request by robert-zaremba**
+ Tendermint v0.34.8 solves the problem with growing log
+ Evidence in v0.41.0 is broken

So this things should be merged and deployed.

### CODE REVIEW

**Comment by aaronc** [comment]
Let's retarget this against the new 0.42

**Comment by amaurym** [comment]
Should we remove the EXPERIMENTAL flag too, since 0.42 does not have authz/feegrant?

**Comment by clevinson** [comment]
Not sure what you mean by remove the EXPERIMENTAL flag? It's justa configuration when building.. Also, we need it in order to not build ecocredit, data module, and group module for the production mainnet.

**Comment by amaurym** [comment]
Oh yeah, forget my comment then, I thought authz & feegrant were also enabled on EXPERIMENTAL=true only.

**Review by amaurym — APPROVED** [review]

**Review by anilCSE — APPROVED** [review]

**Review by aaronc — APPROVED** [review]

**Pull request merged**
