### PR TITLE
Remove colon from regen addresses

### PR DESCRIPTION
**Pull request by atheeshp**
closes: #280

### CODE REVIEW

**Review by anilCSE — APPROVED** [review]
lgtm

**Review by amaurym — APPROVED** [review]
utACK, I didn't check if these changes are exhaustive or not

**Comment by robert-zaremba** [comment]
If we are doing this changes - can we consider making it shorter? Example updates:
* `valoper` -> `vop` or `op`
* `valcons` -> `vcons` or `cons`

**Comment by aaronc** [comment]
> If we are doing this changes - can we consider making it shorter? Example updates:
> 
> * `valoper` -> `vop` or `op`
> 
> * `valcons` -> `vcons` or `cons`

That would be unnecessarily confusing for other cosmos users.

**Review by aaronc — APPROVED** [review]

**Pull request merged**
