### PR TITLE
feat: Add goreleaser 

### PR DESCRIPTION
**Pull request by likhita-809**
Goreleaser adds automation to create a new github release when a new tag is pushed

### CODE REVIEW

**Review by anilCSE — APPROVED** [review]
lgtm, is there a way to test it before merging?

**Comment by likhita-809** [comment]
> lgtm, is there a way to test it before merging?

I have tested it on my fork repo and everthing is working fine

**Review by robert-zaremba — APPROVED** [review]

**Comment by atheeshp** [comment]
> > lgtm, is there a way to test it before merging?
> 
> I have tested it on my fork repo and everthing is working fine

Did we add windows build as well?

**Comment by likhita-809** [comment]
> > > lgtm, is there a way to test it before merging?
> > 
> > 
> > I have tested it on my fork repo and everthing is working fine
> 
> Did we add windows build as well?

No, it is for linux and darwin

**Comment by amaurym** [comment]
> I think we can add windows build in a separate PR, so that this PR can be unblocked. wdyt?

That sounds totally fine to me, let's add windows if users request it.

**Review by atheeshp — APPROVED** [review]

**Pull request merged**
