### PR TITLE
feat!: Update SDK fork to v0.44.0-regen-1 (with perm vesting account)

### PR DESCRIPTION
**Pull request by likhita-809**
Update go.mod to use `v0.44.0-regen-1`

Closes: #521 

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed 
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Review by amaurym — CHANGES_REQUESTED** [review]
the current tag https://github.com/regen-network/cosmos-sdk/tree/v0.44.0-regen-1 is on the wrong commit.

Blocking for now, to avoid an unwanted merge

**Comment by likhita-809** [comment]
> the current tag https://github.com/regen-network/cosmos-sdk/tree/v0.44.0-regen-1 is on the wrong commit.
> 
> Blocking for now, to avoid an unwanted merge

Fixed this. 
tagged on https://github.com/regen-network/cosmos-sdk/commit/e78b091b3d4efa3851610954715bfa0673114900

**Comment by likhita-809** [comment]
> the current tag https://github.com/regen-network/cosmos-sdk/tree/v0.44.0-regen-1 is on the wrong commit.
> 
> Blocking for now, to avoid an unwanted merge

Fixed this. 
tagged on https://github.com/regen-network/cosmos-sdk/commit/e78b091b3d4efa3851610954715bfa0673114900

**Review by amaurym — APPROVED** [review]
lgtm, thanks!

**Review by aleem1314 — CHANGES_REQUESTED** [review]
I think we should update the SDK version in sub-modules too.

**Review by aleem1314 — APPROVED** [review]
lgtm

**Pull request merged**
