### PR TITLE
feat(x/data/v2/client)!: add generate-iri command

### PR DESCRIPTION
**Pull request by aaronc**
## Description

Closes: #XXXX

Testing instructions:
* try `generate-iri` with a `.jsonld` file
* try `generate-iri` with another non RDF file
* try `convert-iri-to-hash` with some IRI
* try `convert-hash-to-iri` with some hash

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed 
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Review by clevinson — COMMENTED** [review]
Looks good!

I've gone ahead and completed the following tests:
- [x] try `file-iri` with a `.jsonld` file
- [x] try `file-iri` with another non RDF file
- [x] try `convert-iri-to-hash` with some IRI
- [x] try `convert-hash-to-iri` with some hash

Two questions / suggestions I have:
1. Is there another command name you were considering besides `regen q data file-iri`? It's not the most clear IMO, but I'm not sure if I could think of a better one... When initially thinking about this, part of me wanted these utility CLI functions to be outside of the `query` subcommand entirely, as they aren't actually querying for any on-chain data. Something like `regen utils iri-from-file` or `regen iri-from-file` or `regen utils file-to-iri` ?
2. when running `regen q data convert-iri-to-hash` it only provides output as as YAML/text. can you add the `--output` flag so that one can set output as JSON? This would make it easier to convert back to an IRI via the corresponding `convert-hash-to-iri` function?

**Comment by aaronc** [comment]
The command already has a -o option.

**Comment by clevinson** [comment]
With other `regen q data` subcommands there is indeed an `- o / --output` option, but not for any of the commands you've added.

See below:

```sh
$ regen q data resolver --help
Query a resolver by its unique identifier.

Usage:
  regen query data resolver [id] [flags]

Examples:
  regen q data resolver 1

Flags:
      --grpc-addr string   the gRPC endpoint to use for this chain
      --grpc-insecure      allow gRPC over insecure channels, if not TLS the server must use TLS
      --height int         Use a specific height to query state at (this can error if the node is pruning state)
  -h, --help               help for resolver
      --node string        <host>:<port> to Tendermint RPC interface for this chain (default "tcp://localhost:26657")
  -o, --output string      Output format (text|json) (default "text")

Global Flags:
      --chain-id string     The network chain ID
      --home string         directory for config and data (default "/Users/cory/.regen")
      --log_format string   The logging format (json|plain) (default "plain")
      --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
      --trace               print out full stack trace on errors
```

versus

```sh
$ regen q data convert-iri-to-hash --help
Convert an IRI to a ContentHash.

Usage:
  regen query data convert-iri-to-hash [iri] [flags]

Examples:
  regen q data convert-iri-to-hash regen:13toVfvC2YxrrfSXWB5h2BGHiXZURsKxWUz72uDRDSPMCrYPguGUXSC.rdf

Flags:
  -h, --help   help for convert-iri-to-hash

Global Flags:
      --chain-id string     The network chain ID
      --home string         directory for config and data (default "/Users/cory/.regen")
      --log_format string   The logging format (json|plain) (default "plain")
      --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
      --trace               print out full stack trace on errors
```

**Comment by aaronc** [comment]
Oh, that's a regression. Try now

**Comment by aaronc** [comment]
Also we can call this something besides `file-iri` if you have suggestions, but I'd rather not introduce a new `utils` command set because then I have to go up to the top level command and add a new command tree and that spreads data module related stuff over more sub-commands. I already find it somewhat counterintuitive that there is `tx data` and `query data` as opposed to `data tx` and `data query`. I'd prefer not to add a third layer of complexity

**Comment by clevinson** [comment]
Thanks fine, I think it'd be nice then to update the description of data query commands (e.g. the display text for `regen q data --help`) to state that it also contains data module utility functions. Can you do that?

Currently it just says "Query commands for the data module."

As for names of the file subcommand, I prefer something that describes the relation btw file & iri.  So either `file-to-iri`, `iri-from-file`, `get-iri-from-file`, `generate-iri`.  With a slight preference amongst these for `generate-iri` (which is in line with our language in `regen-web/iri-gen` package), or `iri-from-file`.

**Comment by aaronc** [comment]
Can you just pick a name and I'll update the PR?

**Comment by clevinson** [comment]
Let's do `generate-iri`

**Comment by aaronc** [comment]
> Let's do `generate-iri`

Updated

**Review by clevinson — APPROVED** [review]
lgtm!

**Pull request merged**
