### PR TITLE
Move cosmwasm into experimental build

### LINKED ISSUE #296: Move cosmwasm into experimental Module

### PR DESCRIPTION
**Pull request by anilCSE**
closes #296

### CODE REVIEW

**Review by amaurym — COMMENTED** [review]
lgtm, some lint fixes needed.

You can only add build flags per file, right? Is there a way to add build flags per line too? (I'm thinking on the `wasmKeeper` field on the App struct.

Also `app/wasm_wrapper.go` can be under the experimental flag too, right?

**Comment by anilCSE** [comment]
> lgtm, some lint fixes needed.
> 
> You can only add build flags per file, right? Is there a way to add build flags per line too? (I'm thinking on the `wasmKeeper` field on the App struct.
> 

Yes we can only add build flags for files

> Also `app/wasm_wrapper.go` can be under the experimental flag too, right?

Oh yes. Thanks, will update

**Review by amaurym — APPROVED** [review]
lgtm, pending on lint check. Maybe we can also add some comments `// only used in experimental builds` for the places where we add `//nolint`

**Review by clevinson — APPROVED** [review]

**Comment by clevinson** [comment]
Is there an easy way to also remove `wasmd` from go.mod when creating stable builds?

The reason I ask is that currently `make localnet-start` is broken on OSX. This is bc of a bug in wasmd where you cannot build for linux (e.g. `GOOS=linux GOARCH=amd64 make build` fails on OSX when go.mod includes wasmd).

If there's a way to have certain dependencies be build-flag dependent that would be awesome.

Regardless we should file an issue with Wasmd, or maybe move to running `make build-linux` in a docker container instaed of using `GOOS=linux GOARCH=amd64` vars.

**Pull request merged**
