### PR TITLE
fix: update go module for regen-ledger to v2

### PR DESCRIPTION
**Pull request by clevinson**
## Description

Currently, projects wanting to import regen-ledger v2.0 as a dependency will not be able to do so without pulling from a git hash & go.mod pseudo-version.  This is because we hadn't incremented the go.mod module version for regen-ledger, and updated relevant imports in app.go.

This PR fixes that issue by adhering to go.mod's [guidelines](https://golang.org/ref/mod#major-version-suffixes).

Note: I had a difficult time verifying explicitly that we don't need to add the version suffix (`v2`) to import paths of packages that are managed by separate go modules with their own go.mod.  But since this all compiles, I'm assuming that this is the correct way to do things, and I didn't to update any import paths for sub-modules like ecocredits to: `gitHub.com/regen-network/regen-ledger/v2/x/ecocredit`.

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed 
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Review by ryanchristo — APPROVED** [review]
Looks good to me.

> I didn't to update any import paths for sub-modules like ecocredits

This is correct as far as I can tell. It makes sense to leave the module path as is for independent modules and only add the `v2` suffix to the module itself when it reaches `v2`.

**Review by robert-zaremba — APPROVED** [review]

**Comment by clevinson** [comment]
@mergify backport `release/v2.0.x`

**Comment by ryanchristo** [comment]
@mergifyio backport release/v2.0.x

**Comment by clevinson** [comment]
@mergify backport release/v2.0.x

**Pull request merged**
