### PR TITLE
feat: devnet for regen-ledger 

### PR DESCRIPTION
**Pull request by PJEstrada**
## Description

Adds a Devnet script using docker compose for running tests against a local network.

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed 
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)__

### CODE REVIEW

**Comment by JeancarloBarrios** [comment]
@PJEstrada I think it LGTM lets just parametrized the validator number

**Review by Moo12332 — APPROVED** [review]
Done

**Review by JeancarloBarrios — CHANGES_REQUESTED** [review]
Let's add the parametrization, and we are good!!

**Comment by PJEstrada** [comment]
> Let's add the parametrization, and we are good!!

Thanks @JeancarloBarrios ! I've added parametrization of node count here https://github.com/regen-network/regen-ledger/pull/2224/commits/fe5d0bd1eb939bc383a3e88546d0d5b87bde1eae

For the initial state my suggestion for now is to rely on the CLI to create state init scripts, mainly because the dynamic creation of the keys between on each start makes the genesis file generation a bit more complex. As this devenet gets more usage we can evaluate if it's worth adding tooling around genesis file state generation  for better developer ergonomics

**Review by JeancarloBarrios — APPROVED** [review]

**Pull request merged**
